{
 "title": "Jellyfish",
 "tags": [ "standard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "integration_type",
    "query": "label_values(jf_mirror_total, type)"
   },
   {
    "name": "action_request_type",
    "query": "label_values(jf_worker_action_request_total, type)"
   },
   {
    "name": "translate_type",
    "query": "label_values(jf_translate_total, type)"
   }
  ]
 },
 "panels": [
  { "title": "jsonschema2sql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Compilation Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (increase(jf_sql_gen_ms[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Compilation Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (increase(jf_sql_gen_ms[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Query Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (increase(jf_query_ms[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max Query Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (increase(jf_query_ms[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Old/New Mismatches (count per min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(jf_compiler_mismatch_total[$__interval])) by (type)"
    }
   ]
  },
  { "title": "Cards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Card Insert (count per min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(jf_card_insert_total[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Card Upsert (count per min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(jf_card_upsert_total[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Card Read (count per min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(jf_card_read_total[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Mirrors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Mirror Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jf_mirror_total{type=~\"$integration_type\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$integration_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(jf_mirror_duration_ms_bucket{type=\"$integration_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$integration_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "repeat": "integration_type",
   "targets": [
    {
     "expr": "sum(increase(jf_mirror_duration_ms_bucket{type=\"$integration_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$integration_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(jf_mirror_duration_ms_bucket{type=\"$integration_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$integration_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(jf_mirror_duration_ms_bucket{type=\"$integration_type\"}[$__interval]))"
    }
   ]
  },
  { "title": "Translates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Translate Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jf_translate_total{type=~\"$translate_type\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$translate_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(increase(jf_translate_duration_ms_bucket{type=\"$translate_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$translate_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "repeat": "translate_type",
   "targets": [
    {
     "expr": "sum(increase(jf_translate_duration_ms_bucket{type=\"$translate_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$translate_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(increase(jf_translate_duration_ms_bucket{type=\"$translate_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$translate_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(jf_translate_duration_ms_bucket{type=\"$translate_type\"}[$__interval]))"
    }
   ]
  },
  { "title": "Action Request Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Action Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jf_worker_action_request_total{type=~\"$action_request_type\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Worker Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jf_worker_saturation{type=~\"$action_request_type\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "repeat": "action_request_type",
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$action_request_type Duration (ms avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "sum(increase(jf_worker_job_duration_ms_bucket{type=\"$action_request_type\"}[$__interval]))"
    }
   ]
  },
  { "title": "Socket.IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Connections Opened",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(socket_io_connect_total{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "opened"
    },
    {
     "expr": "sum(increase(socket_io_disconnect_total{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "Connected (instantaneous at scrape)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(socket_io_connected{app=\"jellyfish\"})",
     "legendFormat": "connected"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(socket_io_events_received_total{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(increase(socket_io_events_sent_total{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(socket_io_errors_total{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "TX/RX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(socket_io_transmit_bytes{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "-sum(increase(socket_io_recieve_bytes{app=\"jellyfish\"}[$__interval]))",
     "legendFormat": "RX"
    }
   ]
  }
 ]
}