FROM resinci/jellyfish-test:v1.3.10

WORKDIR /usr/src/jellyfish
ARG NPM_TOKEN

# Install npm packages, --unsafe-perm flag allows the postinstall script to run correctly
COPY package.json package-lock.json ./
COPY scripts ./scripts
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && \
	PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --unsafe-perm && \
	rm -f ~/.npmrc

# Copy in source and run catch-uncommitted, lint, and unit tests
COPY . ./
RUN make docs/assets/architecture.png ARCHITECTURE.md docker-compose.yml && \
	npx catch-uncommitted --skip-node-versionbot-changes --exclude=VERSION,.versionbot/ && \
	make lint && \
	make test-unit COVERAGE=0
