FROM resinci/jellyfish-test

WORKDIR /usr/src/jellyfish

COPY scripts ./scripts

COPY package.json package-lock.json ./

ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
# --unsafe-perm flag allows the postinstall script to run correctly
RUN PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --unsafe-perm
RUN rm -f ~/.npmrc

COPY . ./

# Run catch-uncommitted.
RUN make docs/assets/architecture.png ARCHITECTURE.md docker-compose.yml && \
	npx catch-uncommitted --skip-node-versionbot-changes --exclude=VERSION,.versionbot/

# Run lint and unit tests.
RUN make lint && make test-unit COVERAGE=0
