FROM scratch AS preface

COPY ./apps/action-server ./apps/action-server

FROM jellyfish-server-base

COPY --from=preface . .

RUN echo "#!/bin/sh" > run.sh && \
	make --dry-run start-tick >> run.sh && \
	chmod +x run.sh && cat run.sh
CMD [ "sh", "run.sh" ]
