version: 0.1
loglevel: debug
log:
  fields:
    service: registry
storage:
  inmemory:
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    #autoredirect: true
    realm: http://192.168.1.145:8000/v1/registry
    service: localhost:5000
    issuer: 192.168.1.145:8000
    rootcertbundle: /root/certs/token.crt
