pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - "status-success=ci/circleci: results"
      - "status-success=ResinCI/docker/build"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
        strict: true
