reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: apps/server/Dockerfile
      docker_repo: balena/jellyfish
      publish: true
    - path: .
      dockerfile: apps/action-server/Dockerfile.tick
      docker_repo: balena/jellyfish-tick-server
      publish: true
    - path: .
      dockerfile: apps/action-server/Dockerfile.worker
      docker_repo: balena/jellyfish-action-server
      publish: true
    - path: .
      dockerfile: apps/ui/Dockerfile
      docker_repo: balena/jellyfish-ui
      publish: true
