reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: test/containers/Dockerfile.test
      docker_repo: balena/jellyfish-ci-test
      publish: false
    - path: .
      dockerfile: apps/server/Dockerfile
      docker_repo: balena/jellyfish
      publish: true
    - path: .
      dockerfile: apps/ui/Dockerfile
      docker_repo: balena/jellyfish-ui
      publish: true
    - path: .
      dockerfile: apps/livechat/Dockerfile
      docker_repo: balena/jellyfish-livechat
      publish: true
