reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/jellyfish
      publish: true
    - path: .
      dockerfile: Dockerfile.tick
      docker_repo: balena/jellyfish-tick-server
      publish: true
    - path: .
      dockerfile: Dockerfile.worker
      docker_repo: balena/jellyfish-action-server
      publish: true
    - path: .
      dockerfile: Dockerfile.ui
      docker_repo: balena/jellyfish-ui
      publish: true
