reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: apps/server/Dockerfile
      docker_repo: balena/jellyfish
      publish: true
    - path: .
      dockerfile: apps/ui/Dockerfile
      docker_repo: balena/jellyfish-ui
      publish: true
    - path: .
      dockerfile: Dockerfile.ci
      docker_repo: balena/jellyfish-sut
      publish: false
