reviewers: 1
docker:
  builds:
    - path: .
      dockerfile: test/containers/Dockerfile.test
      docker_repo: balena/jellyfish-ci-test
      publish: false
    - path: .
      dockerfile: apps/server/Dockerfile
      docker_repo: balena/jellyfish
      publish: true
    - path: .
      dockerfile: apps/action-server/Dockerfile.tick
      docker_repo: balena/jellyfish-tick-server
      publish: true
    - path: .
      dockerfile: apps/action-server/Dockerfile.worker
      docker_repo: balena/jellyfish-action-server
      publish: true
    - path: .
      dockerfile: apps/ui/Dockerfile
      args:
          - SENTRY_DSN_UI=0
          - SERVER_HOST=http://api.ly.fish.local
          - SERVER_PORT=80
      docker_repo: balena/jellyfish-ui
      publish: true
    - path: .
      dockerfile: apps/livechat/Dockerfile
      args:
          - SERVER_HOST=http://api.ly.fish.local
          - SERVER_PORT=80
      docker_repo: balena/jellyfish-livechat
      publish: true
