version: '2.1'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - api
      - livechat
      - postgres
      - ui
      - balena-mdns-publisher
    environment:
      - DATABASE=postgres
      - LIVECHAT_HOST=http://livechat
      - LIVECHAT_PORT=80
      - NODE_ENV=test
      - POSTGRES_DATABASE=jellyfish
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - SERVER_HOST=http://api
      - SERVER_PORT=8000
      - UI_HOST=http://ui
      - UI_PORT=80
      - INTEGRATION_BALENA_API_OAUTH_BASE_URL=https://api.balena-cloud.com
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - INTEGRATION_DISCOURSE_SIGNATURE_KEY=foobar
      - INTEGRATION_DISCOURSE_TOKEN=foobar
      - INTEGRATION_DISCOURSE_USERNAME=foobar
      - INTEGRATION_BALENA_API_PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2NDTU5RdXYwTTZ0SFhxZVgKSTFxTmg5aUxHWGUyTE1TUHBubmx5dTM3V3dPaFJBTkNBQVNFeU83MU1JU1BvNXhoUy85TzRyWDdoeWFxSExEMgozaFBUNC9rOXdtVHEzbk1Vbk1LQXFHQWRUbTE1TThTS1BPVTM0ZGN4LzJucFd0LzNkMjVobDM3ZwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      - INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaE1qdTlUQ0VqNk9jWVV2L1R1SzErNGNtcWh5dwo5dDRUMCtQNVBjSms2dDV6Rkp6Q2dLaGdIVTV0ZVRQRWlqemxOK0hYTWY5cDZWcmY5M2R1WVpkKzRBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
      - INTEGRATION_BALENA_API_PUBLIC_KEY_STAGING=foobar
      - INTEGRATION_FLOWDOCK_SIGNATURE_KEY=foobar
      - INTEGRATION_FLOWDOCK_TOKEN=foobar
      - INTEGRATION_GITHUB_SIGNATURE_KEY=foobar
      - INTEGRATION_GITHUB_TOKEN=foobar
      - INTEGRATION_INTERCOM_TOKEN=foobar
      - INTEGRATION_OUTREACH_APP_ID=foobar
      - INTEGRATION_OUTREACH_APP_SECRET=foobar
      - INTEGRATION_OUTREACH_SIGNATURE_KEY=buzzbaz
      - INTEGRATION_FRONT_TOKEN=foobar
      - SCRUB=0
      - COVERAGE=0
    networks:
      - internal
