FROM balena/open-balena-base:v9.4.1

WORKDIR /usr/src/jellyfish

COPY scripts/check_node_version.js scripts/check_node_version.js
COPY package.json package-lock.json ./
ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && \
    cat ~/.npmrc && \
    env && \
    NODE_ENV=production npm ci && \
    rm -f ~/.npmrc

COPY Makefile .
