version: '2.1'

services:
  registry:
    image: balena/open-balena-registry:master
    expose:
      - 80
    networks:
      - internal
    restart: always
    environment:
      - BALENA_TOKEN_AUTH_ISSUER=${REGISTRY_TOKEN_AUTH_CERT_ISSUER:?missing}
      - BALENA_TOKEN_AUTH_REALM=http://api.ly.fish.local/v1/registry
      - BALENA_REGISTRY2_HOST=registry.ly.fish.local
      - REGISTRY2_SECRETKEY=foobar
      - "REGISTRY2_CACHE_ENABLED=false"
      - REGISTRY2_STORAGEPATH=/data
      # base64 encoded root cert bundle
      - API_TOKENAUTH_CRT
      # required for open-balena-base
      - CONFD_BACKEND=ENV
    tmpfs:
      - /data
      # required for open-balena-base
      - /run
      - /sys/fs/cgroup
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    # required for open-balena-base
    privileged: true
    # required for open-balena-base
    stop_signal: SIGRTMIN+3

  # overwrite haproxy config to include registry
  haproxy:
    networks:
      internal:
        aliases:
          - jel.ly.fish.local
          - livechat.ly.fish.local
          - api.ly.fish.local
          - registry.ly.fish.local
    environment:
      PROXY_CONFIG: ewoJImRlZmF1bHRzIjogWwoJCSJ0aW1lb3V0IGNvbm5lY3QgNTAwMCIsCgkJInRpbWVvdXQgY2xpZW50IDYwMDAwIiwKCQkidGltZW91dCBzZXJ2ZXIgNjAwMDAiLAoJCSJkZWZhdWx0LXNlcnZlciBpbml0LWFkZHIgbGFzdCxsaWJjLG5vbmUiCgldLAoJInJlc29sdmVycyI6IFsKCQl7CgkJCSJpZCI6ICJkb2NrZXItYnJpZGdlLXJlc29sdmVyIiwKCQkJIm5hbWVzZXJ2ZXJzIjogewoJCQkJImRvY2tlci1yZXNvbHZlciI6ICIxMjcuMC4wLjExOjUzIgoJCQl9LAoJCQkiaG9sZCI6IHsKCQkJCSJ2YWxpZCI6ICIwbXMiCgkJCX0KCQl9CgldLAoJInVpIjogewoJCSJiYWNrZW5kIjogWwoJCQl7CgkJCQkidXJsIjogImh0dHA6Ly91aTo4MCIsCgkJCQkic2VydmVyIjogewoJCQkJCSJyZXNvbHZlcnMiOiAiZG9ja2VyLWJyaWRnZS1yZXNvbHZlciIsCgkJCQkJInJlc29sdmUtcHJlZmVyIjogImlwdjQiLAoJCQkJCSJjaGVjayI6IG51bGwsCgkJCQkJInBvcnQiOiAiPHBvcnQ+IgoJCQkJfQoJCQl9CgkJXSwKCQkiZnJvbnRlbmQiOiBbCgkJCXsKCQkJCSJwcm90b2NvbCI6ICJodHRwIiwKCQkJCSJkb21haW4iOiAibHkuZmlzaC5sb2NhbCIsCgkJCQkic3ViZG9tYWluIjogImplbCIsCgkJCQkicG9ydCI6ICI4MCIKCQkJfQoJCV0KCX0sCgkicmVkaXMiOiB7CgkJImJhY2tlbmQiOiBbCgkJCXsKCQkJCSJ1cmwiOiAiaHR0cDovL3JlZGlzOjYzNzkiLAoJCQkJInNlcnZlciI6IHsKCQkJCQkicmVzb2x2ZXJzIjogImRvY2tlci1icmlkZ2UtcmVzb2x2ZXIiLAoJCQkJCSJyZXNvbHZlLXByZWZlciI6ICJpcHY0IiwKCQkJCQkiY2hlY2siOiBudWxsLAoJCQkJCSJwb3J0IjogIjxwb3J0PiIKCQkJCX0KCQkJfQoJCV0sCgkJImZyb250ZW5kIjogWwoJCQl7CgkJCQkicHJvdG9jb2wiOiAiaHR0cCIsCgkJCQkiZG9tYWluIjogImx5LmZpc2gubG9jYWwiLAoJCQkJInN1YmRvbWFpbiI6ICJyZWRpcyIsCgkJCQkicG9ydCI6ICI2Mzc5IgoJCQl9CgkJXQoJfSwKCSJwb3N0Z3JlcyI6IHsKCQkiYmFja2VuZCI6IFsKCQkJewoJCQkJInVybCI6ICJodHRwOi8vcG9zdGdyZXM6NTQzMiIsCgkJCQkic2VydmVyIjogewoJCQkJCSJyZXNvbHZlcnMiOiAiZG9ja2VyLWJyaWRnZS1yZXNvbHZlciIsCgkJCQkJInJlc29sdmUtcHJlZmVyIjogImlwdjQiLAoJCQkJCSJjaGVjayI6IG51bGwsCgkJCQkJInBvcnQiOiAiPHBvcnQ+IgoJCQkJfQoJCQl9CgkJXSwKCQkiZnJvbnRlbmQiOiBbCgkJCXsKCQkJCSJwcm90b2NvbCI6ICJodHRwIiwKCQkJCSJkb21haW4iOiAibHkuZmlzaC5sb2NhbCIsCgkJCQkic3ViZG9tYWluIjogInBvc3RncmVzIiwKCQkJCSJwb3J0IjogIjU0MzIiCgkJCX0KCQldCgl9LAoJImxpdmVjaGF0IjogewoJCSJiYWNrZW5kIjogWwoJCQl7CgkJCQkidXJsIjogImh0dHA6Ly9saXZlY2hhdDo4MCIsCgkJCQkic2VydmVyIjogewoJCQkJCSJyZXNvbHZlcnMiOiAiZG9ja2VyLWJyaWRnZS1yZXNvbHZlciIsCgkJCQkJInJlc29sdmUtcHJlZmVyIjogImlwdjQiLAoJCQkJCSJjaGVjayI6IG51bGwsCgkJCQkJInBvcnQiOiAiPHBvcnQ+IgoJCQkJfQoJCQl9CgkJXSwKCQkiZnJvbnRlbmQiOiBbCgkJCXsKCQkJCSJwcm90b2NvbCI6ICJodHRwIiwKCQkJCSJkb21haW4iOiAibHkuZmlzaC5sb2NhbCIsCgkJCQkic3ViZG9tYWluIjogImxpdmVjaGF0IiwKCQkJCSJwb3J0IjogIjgwIgoJCQl9CgkJXQoJfSwKCSJhcGkiOiB7CgkJImJhY2tlbmQiOiBbCgkJCXsKCQkJCSJ1cmwiOiAiaHR0cDovL2FwaTo4MDAwIiwKCQkJCSJzZXJ2ZXIiOiB7CgkJCQkJInJlc29sdmVycyI6ICJkb2NrZXItYnJpZGdlLXJlc29sdmVyIiwKCQkJCQkicmVzb2x2ZS1wcmVmZXIiOiAiaXB2NCIsCgkJCQkJImNoZWNrIjogbnVsbCwKCQkJCQkicG9ydCI6ICI8cG9ydD4iCgkJCQl9CgkJCX0KCQldLAoJCSJmcm9udGVuZCI6IFsKCQkJewoJCQkJInByb3RvY29sIjogImh0dHAiLAoJCQkJImRvbWFpbiI6ICJseS5maXNoLmxvY2FsIiwKCQkJCSJzdWJkb21haW4iOiAiYXBpIiwKCQkJCSJwb3J0IjogIjgwIgoJCQl9CgkJXQoJfSwKCSJyZWdpc3RyeSI6IHsKCQkiYmFja2VuZCI6IFsKCQkJewoJCQkJInVybCI6ICJodHRwOi8vcmVnaXN0cnk6ODAiLAoJCQkJInNlcnZlciI6IHsKCQkJCQkicmVzb2x2ZXJzIjogImRvY2tlci1icmlkZ2UtcmVzb2x2ZXIiLAoJCQkJCSJyZXNvbHZlLXByZWZlciI6ICJpcHY0IiwKCQkJCQkiY2hlY2siOiBudWxsLAoJCQkJCSJwb3J0IjogIjxwb3J0PiIKCQkJCX0KCQkJfQoJCV0sCgkJImZyb250ZW5kIjogWwoJCQl7CgkJCQkicHJvdG9jb2wiOiAiaHR0cCIsCgkJCQkiZG9tYWluIjogImx5LmZpc2gubG9jYWwiLAoJCQkJInN1YmRvbWFpbiI6ICJyZWdpc3RyeSIsCgkJCQkicG9ydCI6ICI4MCIKCQkJfQoJCV0KCX0KfQoK
