version: '2.1'

services:
  registry:
    image: balena/open-balena-registry:master
    expose:
      - 80
    networks:
      - internal
    restart: always
    environment:
      - API_TOKENAUTH_CRT=${REGISTRY_TOKEN_AUTH_CERT:?missing}
      - BALENA_TOKEN_AUTH_ISSUER=${REGISTRY_TOKEN_AUTH_CERT_ISSUER:?missing}
      - BALENA_TOKEN_AUTH_REALM=${REGISTRY_TOKEN_AUTH_REALM:?missing}
      - BALENA_REGISTRY2_HOST=${REGISTRY_HOST:?missing}
      - REGISTRY2_SECRETKEY=${REGISTRY_SECRETKEY:?missing}
      - REGISTRY2_CACHE_ENABLED
      - REGISTRY2_STORAGEPATH=/data
      # required for open-balena-base
      - CONFD_BACKEND=ENV
    tmpfs:
      # TODO
      - /data
      # required for open-balena-base
      - /run
      - /sys/fs/cgroup
    # required for open-balena-base
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    privileged: true
    stop_signal: SIGRTMIN+3
