version: '2.1'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        NPM_TOKEN: $NPM_TOKEN
    depends_on:
      - api
      - livechat
      - postgres
      - ui
      - balena-mdns-publisher
    environment:
      - DATABASE=postgres
      - LOGLEVEL=crit
      - LIVECHAT_HOST=http://livechat
      - LIVECHAT_PORT=80
      - NODE_ENV=test
      - POSTGRES_DATABASE=jellyfish
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - SERVER_HOST=http://api
      - SERVER_PORT=80
      - UI_HOST=http://ui
      - UI_PORT=80
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - SCRUB=0
      - COVERAGE=0
      - CI=1
      - FS_DRIVER
      - AWS_ACCESS_KEY_ID
      - AWS_S3_BUCKET_NAME
      - AWS_SECRET_ACCESS_KEY
      - OAUTH_REDIRECT_BASE_URL=https://jel.ly.fish
      - INTEGRATION_BALENA_API_OAUTH_BASE_URL=https://api.balena-cloud.com
      - INTEGRATION_BALENA_API_PRIVATE_KEY
      - INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION
      - INTEGRATION_BALENA_API_PUBLIC_KEY_STAGING=foobar
      - INTEGRATION_DEFAULT_USER
      - INTEGRATION_DISCOURSE_SIGNATURE_KEY
      - INTEGRATION_DISCOURSE_TOKEN
      - INTEGRATION_DISCOURSE_USERNAME
      - INTEGRATION_FLOWDOCK_SIGNATURE_KEY
      - INTEGRATION_FLOWDOCK_TOKEN
      - INTEGRATION_FRONT_TOKEN
      - INTEGRATION_GITHUB_APP_ID
      - INTEGRATION_GITHUB_PRIVATE_KEY
      - INTEGRATION_GITHUB_SIGNATURE_KEY
      - INTEGRATION_GITHUB_TOKEN
      - INTEGRATION_GOOGLE_MEET_CREDENTIALS
      - INTEGRATION_INTERCOM_TOKEN
      - INTEGRATION_OUTREACH_APP_ID
      - INTEGRATION_OUTREACH_APP_SECRET
      - INTEGRATION_OUTREACH_SIGNATURE_KEY
      - INTEGRATION_TYPEFORM_SIGNATURE_KEY
      - MAILGUN_BASE_URL
      - MAILGUN_DOMAIN
      - MAILGUN_TOKEN
      - MONITOR_SECRET_TOKEN
      - NPM_TOKEN
      - RESET_PASSWORD_SECRET_TOKEN
    networks:
      - internal
