FROM resinci/jellyfish-test as base

WORKDIR /usr/src/app
RUN npm install --global partial-install
COPY . /usr/src/app
RUN partial-install apps/action-server/tick.js /usr/src/app
RUN npm ci

CMD [ "make", "start-tick" ]
