###########################################################
# Runtime
###########################################################

FROM resinci/jellyfish-base:3daf0d44

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN NODE_ENV=production npm ci
COPY . /usr/src/app

CMD [ "make", "start-worker" ]
