version: '2.1'

services:
  oauth-provider-example:
    build:
      context: ./apps/oauth-provider-example
    networks:
      - internal
    expose:
      - 80
  sut:
    image: balena/jellyfish-sut
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        NPM_TOKEN: $NPM_TOKEN
    depends_on:
      - api
      - livechat
      - postgres
      - ui
      - balena-mdns-publisher
      - oauth-provider-example
    environment:
      - NODE_ENV
      - SERVER_HOST=http://api
    secrets:
      - aws_access_key_id
      - aws_s3_bucket_name
      - aws_secret_access_key
      - integration_balena_api_private_key
      - integration_balena_api_public_key_production
      - integration_balena_api_public_key_staging
      - integration_balena_api_app_id
      - integration_balena_api_app_secret
      - integration_discourse_signature_key
      - integration_discourse_token
      - integration_discourse_username
      - integration_flowdock_signature_key
      - integration_flowdock_token
      - integration_front_token
      - integration_github_app_id
      - integration_github_private_key
      - integration_github_signature_key
      - integration_github_token
      - integration_google_meet_credentials
      - integration_intercom_token
      - integration_outreach_app_id
      - integration_outreach_app_secret
      - integration_outreach_signature_key
      - integration_typeform_signature_key
      - mailgun_token
      - reset_password_secret_token
      - registry_token_auth_cert_key
      - registry_token_auth_cert_kid
    networks:
      - internal
