version: '3'

output: 'prefixed'

env:
  NODE_ENV: production

tasks:
  catch-uncommitted:
    cmds:
      - make docs/assets/architecture.png ARCHITECTURE.md docker-compose.yml
      - npx catch-uncommitted --skip-node-versionbot-changes --exclude=VERSION,.versionbot/

  lint-server:
    dir: apps/server
    cmds:
      - npm run lint

  lint-livechat:
    dir: apps/livechat
    cmds:
      - npm run lint

  lint-ui:
    dir: apps/ui
    cmds:
      - npm run lint

  lint:
    cmds:
      - npm run lint
      - task: lint-server
      - task: lint-livechat
      - task: lint-ui

  unit-server:
    dir: apps/server
    cmds:
      - npm run test:unit

  unit-ui:
    dir: apps/ui
    cmds:
      - npm run test

  unit:
    cmds:
      - task: unit-ui
      - task: unit-server

  wait-for-api:
    cmds:
      - ./scripts/ci/wait-for-api.sh

  e2e-sdk:
    env:
      LOGLEVEL: warning
    cmds:
      - npm run test:e2e:sdk

  e2e-livechat:
    env:
      LOGLEVEL: warning
    cmds:
      - npm run test:e2e:livechat

  e2e-ui:
    cmds:
      - INTEGRATION_OUTREACH_APP_ID= make test-e2e-ui

  e2e-server:
    cmds:
      - make test-e2e-server

  e2e:
    deps: [e2e-sdk, e2e-livechat, e2e-server]

  integration-server:
    cmds:
      - SERVER_HOST=http://localhost make test-integration-server

  export-database:
    cmds:
      - ./scripts/ci/postgres/export.js e2e-server

  import-database:
    cmds:
      - ./scripts/ci/postgres/import.js e2e-server

  e2e-server-previous-dump:
    cmds:
      - make test FILES=./test/e2e/server/index.spec.js

  post-summary:
    cmds:
      - ./scripts/ci/summary.js

  test:
    cmds:
      - task: catch-uncommitted
      - task: lint
      - task: unit
      - task: wait-for-api
      - task: e2e
      - task: e2e-ui
      - task: integration-server
      - task: export-database
      - task: import-database
      - task: e2e-server-previous-dump
      - task: post-summary
