version: "3"

output: "prefixed"

env:
  NODE_ENV: production

tasks:
  catch-uncommitted:
    cmds:
      - npm run docs:diagram
      - npm run docs:summary
      - npm run lint:catch

  lint:
    cmds:
      - npm run lint

  wait-for-api:
    cmds:
      - ./scripts/ci/wait-for-api.sh

  e2e-sdk:
    cmds:
      - npm run test:e2e:sdk

  e2e-ui:
    cmds:
      - npm run test:e2e:ui

  e2e-server:
    cmds:
      - npm run test:e2e:server

  e2e:
    deps: [e2e-sdk, e2e-server]

  integration-server:
    cmds:
      - npm run test:integration:server

  test:
    cmds:
      - task: catch-uncommitted
      - task: lint
      - task: unit
      - task: wait-for-api
      - task: integration-server
      - task: e2e
      - task: e2e-ui
