version: '3'

output: 'prefixed'

env:
  NODE_ENV: production

tasks:
  catch-uncommitted:
    cmds:
      - npm run docs:diagram
      - npm run docs:summary
      - npm run lint:catch

  lint:
    cmds:
      - npm run lint

  unit:
    cmds:
      - npm run test:unit

  wait-for-api:
    cmds:
      - ./scripts/ci/wait-for-api.sh

  e2e-sdk:
    cmds:
      - npm run test:e2e:sdk

  e2e-ui:
    cmds:
      - npm run test:e2e:ui

  e2e-server:
    cmds:
      - npm run test:e2e:server

  e2e:
    deps: [e2e-sdk, e2e-server]

  integration-server:
    cmds:
      - npm run test:integration:server

  export-database:
    cmds:
      - ./scripts/ci/postgres/export.js e2e-server

  import-database:
    cmds:
      - ./scripts/ci/postgres/import.js e2e-server

  e2e-server-previous-dump:
    cmds:
      - task: e2e-server

  benchmark:
    cmds:
      - cmd: hyperfine --runs 3 'npm run test:benchmark'
        ignore_errors: true

  test:
    cmds:
      - task: catch-uncommitted
      - task: lint
      - task: unit
      - task: wait-for-api
      - task: integration-server
      - task: e2e
      - task: e2e-ui
      - task: export-database
      - task: import-database
      - task: e2e-server-previous-dump
      - task: benchmark
