/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

/* global env */

// The _env_ object is generated by `env.sh` at runtime.
// eslint-disable-next-line
const windowEnv = (typeof window !== 'undefined' && window._env_) ?
	// eslint-disable-next-line
	window._env_ :
	{}

export const isTest = () => {
	return env.NODE_ENV === 'test'
}

export const isProduction = () => {
	return env.NODE_ENV === 'production'
}

export const sentry = {
	dsn: windowEnv.SENTRY_DSN_UI || '0'
}

export const api = {
	prefix: 'api/v2',
	url: (typeof window === 'undefined')
		? ''
		: (`${windowEnv.SERVER_HOST}:${windowEnv.SERVER_PORT}` || window.location.origin)
}

export const analytics = {
	mixpanel: {
		token: (typeof env === 'undefined') ? '' : (env.MIXPANEL_TOKEN_UI || '')
	}
}

export const version = (typeof env === 'undefined') ? 'v1.0.0' : (env.VERSION || 'v1.0.0')

export const pwa = {
	debugSW: () => {
		return (typeof env === 'undefined') ? false : (env.JF_DEBUG_SW === '1')
	}
}
