apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jellyfish
  namespace: jellyfish
spec:
  selector:
    matchLabels:
      app: jellyfish
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfish
    spec:
      containers:
      - image: {{{jellyfish-application-image}}}
        name: jellyfish
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 8
        readinessProbe:
          httpGet:
            path: /ping
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 8
          failureThreshold: 30
        env:
        - name: PORT
          value: 8000
        - name: DATABASE
          value: postgres
        - name: POSTGRES_DATABASE
          value: {{POSTGRES_DATABASE}}
        - name: POSTGRES_USER
          value: {{POSTGRES_USER}}
        - name: POSTGRES_PASSWORD
          value: {{POSTGRES_PASSWORD}}
        - name: POSTGRES_PORT
          value: {{POSTGRES_PORT}}
        - name: POSTGRES_HOST
          value: {{POSTGRES_HOST}}
        - name: REDIS_HOST
          value: {{REDIS_HOST}}
        - name: REDIS_PASSWORD
          value: {{{REDIS_PASSWORD}}}
        - name: NODE_ENV
          value: {{{NODE_ENV}}}
        - name: SENTRY_DSN_SERVER
          value: {{{SENTRY_DSN_SERVER}}}
        - name: LOGENTRIES_TOKEN
          value: {{{LOGENTRIES_TOKEN}}}
        - name: INTEGRATION_FRONT_TOKEN
          value: {{{INTEGRATION_FRONT_TOKEN}}}
        - name: INTEGRATION_GITHUB_TOKEN
          value: {{{INTEGRATION_GITHUB_TOKEN}}}
        - name: INTEGRATION_GITHUB_SIGNATURE_KEY
          value: {{{INTEGRATION_GITHUB_SIGNATURE_KEY}}}
        ports:
        - containerPort: 8000
          name: jellyfish-api
      imagePullSecrets:
        - name: com.docker.hub.travisciresin
