apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jellyfish
  namespace: jellyfish
spec:
  selector:
    matchLabels:
      app: jellyfish
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfish
    spec:
      containers:
      - image: {{{jellyfish-application-image}}}
        name: jellyfish
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: rethinkdb 
        - name: DB_USER
          value: {{{DB_USER}}}
        - name: DB_PASSWORD
          value: {{{DB_PASSWORD}}}
        ports:
        - containerPort: 8000
          name: jellyfish-api
      imagePullSecrets:
        - name: com.docker.hub.travisciresin
