apiVersion: v1
kind: Service
metadata:
  labels:
    name: rethinkdb
  name: rethinkdb
  namespace: jellyfish
spec:
  selector:
    app: rethinkdb
  ports:
  - port: 28015
    name: data-port
  - port: 8080
    name: db-ui-port
