apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rethinkdb
  namespace: jellyfish
spec:
  selector:
    matchLabels:
      app: rethinkdb
  replicas: 3
  serviceName: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb
    spec:
      containers:
      - image: {{{jellyfish-rethinkdb-image}}}
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: DB_PASSWORD
          value: {{{DB_PASSWORD}}}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: RETHINK_CLUSTER
          value: rethinkdb
        ports:
        - containerPort: 29015
          name: cluster-port
        - containerPort: 28015
          name: client-port
        - containerPort: 8080
          name: admin-port
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: fast
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
