---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rethinkdb-pv-claim
  namespace: jellyfish
spec:
  storageClassName: fast 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

