---
properties:
  - JELLYFISH_HOST:
      type: hostname
  - POSTGRES_DATABASE:
      type: string
  - POSTGRES_USER:
      type: string
  - POSTGRES_PASSWORD:
      type: string
  - POSTGRES_PORT:
      type: string
  - POSTGRES_HOST:
      type: hostname
  - REDIS_HOST:
      type: hostname
  - REDIS_PASSWORD:
      type: string
      default:
        eval: GENERATE_API_KEY({length: 24})
  - NODE_ENV:
      type: string
  - SENTRY_DSN_SERVER:
      type: string
  - LOGENTRIES_TOKEN:
      type: string
  - LOGLEVEL:
      type: string
      enum:
        - error
        - info
        - debug
  - INTEGRATION_FRONT_TOKEN:
      type: string
  - INTEGRATION_GITHUB_TOKEN:
      type: string
  - INTEGRATION_GITHUB_SIGNATURE_KEY:
      type: string
