AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBStackName:
    Description: >-
      Please enter the name of the CloudFormation stack that was used to deploy
      the RDS DB resource.
    Type: String
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t3.small
    AllowedValues:
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
      - db.t3.2xlarge
    ConstraintDescription: must select a valid database instance type.
Resources:
  JellyfishAnalyticsDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Jellyfish Analytics DB Parameter group
      Family: postgres10
      Parameters:
        autovacuum_analyze_scale_factor: '0.1'
        autovacuum_naptime: '60'
        autovacuum_vacuum_scale_factor: '0.2'
        log_autovacuum_min_duration: '100'
        log_min_duration_statement: '200'
        max_connections: '1000'
        max_standby_streaming_delay: '-1'
        statement_timeout: '0'
  JellyfishAnalyticsDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      SourceDBInstanceIdentifier: !ImportValue
        Fn::Sub: "${DBStackName}-JellyfishDB"
      DBInstanceIdentifier: jellyfish-analytics
      DBInstanceClass: !Ref DBInstanceClass
      DBParameterGroupName: !Ref JellyfishAnalyticsDBParameterGroup
      Tags:
        - Key: Name
          Value: jellyfish-analytics
