apiVersion: 1

datasources:
  - name: "prometheus"
    type: "prometheus"
    url: "http://prometheus:9090"
    access: "proxy"
    isDefault: true
    jsonData: {}
    readOnly: false
    basicAuth: false
    password: ""
    user: ""
