version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "puppeteer"
          version_requirement: ">= 2.1.a, < 2.2"
    commit_message:
      prefix: "patch"
