{
 "title": "Jellyfish Logs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "jellyfish",
   "type": "logs",
   "description": "Jellyfish API pods",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{name=\"jellyfish\", source_type=\"kubernetes_logs\"} != \"kube-probe\" != \"ELB-HealthChecker\""
    }
   ]
  },
  {
   "title": "action-server",
   "type": "logs",
   "description": "Jellyfish Action Server pods",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{name=\"action-server\", source_type=\"kubernetes_logs\"} != \"kube-probe\" != \"ELB-HealthChecker\""
    }
   ]
  },
  {
   "title": "tick-server",
   "type": "logs",
   "description": "Jellyfish tick-server pods",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{name=\"tick-server\", source_type=\"kubernetes_logs\"} != \"kube-probe\" != \"ELB-HealthChecker\""
    }
   ]
  },
  {
   "title": "jellyfish-livechat",
   "type": "logs",
   "description": "Jellyfish livechat pods",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{name=\"jellyfish-livechat\", source_type=\"kubernetes_logs\"} != \"kube-probe\" != \"ELB-HealthChecker\""
    }
   ]
  },
  {
   "title": "jellyfish-ui",
   "type": "logs",
   "description": "Jellyfish UI pods",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{name=\"jellyfish-ui\", source_type=\"kubernetes_logs\"} != \"kube-probe\" != \"ELB-HealthChecker\""
    }
   ]
  }
 ]
}