apiVersion: v1
kind: Service
metadata:
  labels:
    name: jellyfish-api
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
  name: jellyfish-api
spec:
  selector:
    app: jellyfish
  ports:
  - port: 8000
  sessionAffinity: ClientIP
