{
 "title": "Jellyfish",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "integration_type",
    "query": {
     "query": "label_values(jf_mirror_total, type)"
    }
   },
   {
    "name": "action_request_type",
    "query": {
     "query": "label_values(jf_worker_action_request_total, type)"
    }
   },
   {
    "name": "translate_type",
    "query": {
     "query": "label_values(jf_translate_total, type)"
    }
   },
   {
    "name": "card_type",
    "query": {
     "query": "label_values(jf_card_patch_duration_seconds_count, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compilation Time - Action Server",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(jf_sql_gen_duration_seconds_bucket{pod=~\"action-server-.+\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Query Time - Action Server",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(jf_query_duration_seconds_bucket{pod=~\"action-server-.+\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Compilation Time - Jellyfish",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(jf_sql_gen_duration_seconds_bucket{pod=~\"jellyfish-.+\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Query Time - Jellyfish",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(jf_query_duration_seconds_bucket{pod=~\"jellyfish-.+\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Card Insert Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(jf_card_insert_total[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Card Upsert Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(jf_card_upsert_total[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Card Read Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(jf_card_read_total[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Card Patch Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(jf_card_patch_total[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Card Patch Failure Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (increase(jf_card_patch_failure_total[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
     "repeat": "card_type",
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 76 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 86 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 86 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 96 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 96 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Card Patch Duration: $card_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(jf_card_patch_duration_seconds_bucket{type=\"$card_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mirrors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mirror Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_mirror_total{type=~\"$integration_type\"}[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration: $integration_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "repeat": "integration_type",
     "targets": [
      {
       "expr": "sum(increase(jf_mirror_duration_seconds_bucket{type=\"$integration_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $integration_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(jf_mirror_duration_seconds_bucket{type=\"$integration_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $integration_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(increase(jf_mirror_duration_seconds_bucket{type=\"$integration_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $integration_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(increase(jf_mirror_duration_seconds_bucket{type=\"$integration_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translate Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_translate_total{type=~\"$translate_type\"}[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Duration: $translate_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "repeat": "translate_type",
     "targets": [
      {
       "expr": "sum(increase(jf_translate_duration_seconds_bucket{type=\"$translate_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $translate_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(jf_translate_duration_seconds_bucket{type=\"$translate_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $translate_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(jf_translate_duration_seconds_bucket{type=\"$translate_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $translate_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(jf_translate_duration_seconds_bucket{type=\"$translate_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration: $translate_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(increase(jf_translate_duration_seconds_bucket{type=\"$translate_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Action Request Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Action Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_worker_action_request_total{type=~\"$action_request_type\"}[$__interval])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Worker Queue Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jf_worker_saturation{type=~\"$action_request_type\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "repeat": "action_request_type",
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average Duration: $action_request_type",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(increase(jf_worker_job_duration_seconds_bucket{type=\"$action_request_type\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Socket.IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Opened",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(socket_io_connect_total{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "opened"
      },
      {
       "expr": "sum(increase(socket_io_disconnect_total{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "closed"
      }
     ]
    },
    {
     "title": "Connected (instantaneous at scrape)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(socket_io_connected{app=\"jellyfish\"})",
       "legendFormat": "connected"
      }
     ]
    },
    {
     "title": "Events",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(socket_io_events_received_total{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "received"
      },
      {
       "expr": "sum(increase(socket_io_events_sent_total{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "sent"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(socket_io_errors_total{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "TX/RX",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(socket_io_transmit_bytes{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "TX"
      },
      {
       "expr": "-sum(increase(socket_io_recieve_bytes{app=\"jellyfish\"}[$__interval]))",
       "legendFormat": "RX"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream Saturation (by actor)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(actor) (jf_streams_saturation)",
       "legendFormat": "{{actor}}"
      }
     ]
    },
    {
     "title": "Stream Saturation (by table)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(table) (jf_streams_saturation)",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Stream Link Query / second (by actor)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(actor) (rate(jf_streams_link_query_total[1m]))",
       "legendFormat": "{{actor}}"
      }
     ]
    },
    {
     "title": "Stream Link Query / second (by change type)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(type) (rate(jf_streams_link_query_total[1m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stream Link Query / second (by card type)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(card) (rate(jf_streams_link_query_total[1m]))",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "Stream Link Query / second (by table)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(table) (rate(jf_streams_link_query_total[1m]))",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Stream Errors / second (by actor)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(actor) (rate(jf_streams_error_total[1m]))",
       "legendFormat": "{{actor}}"
      }
     ]
    },
    {
     "title": "Stream Errors / second (by table)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(table) (rate(jf_streams_error_total[1m]))",
       "legendFormat": "{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/query Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_query_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_query_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_query_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/action Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_action_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_action_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_action_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/slug Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_slug_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_slug_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_slug_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/id Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_id_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_id_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_id_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/type Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_type_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_type_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_api_type_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "/whoami Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_whoami_query_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failure Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(jf_http_whoami_query_failure_total[$__interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(jf_http_whoami_query_duration_seconds_bucket[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}