---
# (TBC) remove jellyfish-livechat service after DNS change to ALB
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jellyfish-livechat
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
  name: jellyfish-livechat
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:491725000532:certificate/f9995922-ae03-48eb-8fd1-c6ebe891eaf2
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "63"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: '{{{JELLYFISH_LIVECHAT_HOST}}}'
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  type: LoadBalancer
  selector:
    app: jellyfish-livechat
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
      name: https
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    # (TBC) rename to jellyfish-livechat after DNS change to ALB
    name: jellyfish-livechat-clusterip
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
  # (TBC) rename to jellyfish-livechat after DNS change to ALB
  name: jellyfish-livechat-clusterip
spec:
  selector:
    app: jellyfish-livechat
  ports:
  - port: 80
  sessionAffinity: ClientIP
