apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{{KATAPULT_KUBE_NAMESPACE}}}
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: <<%&children.sw.containerized-application.rabbitmq.data.assets.image.url%>>
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{{RABBITMQ_USERNAME}}}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{{RABBITMQ_PASSWORD}}}
          ports:
            - containerPort: 5672
              name: data-port
      imagePullSecrets:
        - name: com.docker.hub.travisciresin
