apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-storage
  namespace: {{{KATAPULT_KUBE_NAMESPACE}}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
