apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
  namespace: {{{KATAPULT_KUBE_NAMESPACE}}}
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: data-port
