apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: <<%&children.sw.containerized-application.jellyfish-redis.data.assets.image.url%>>
          name: redis
          env:
            - name: REDIS_PASSWORD
              value: '{{{REDIS_PASSWORD}}}'
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: com.docker.hub.travisciresin
