---
apiVersion: v1
data:
  HTTP_TICK_PORT: "8001"
  LOGLEVEL: "info"
  NODE_ENV: "production"
  UV_THREADPOOL_SIZE: "128"
kind: ConfigMap
metadata:
  name: tick-server
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
