---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  JellyfishDBAllocatedStorage:
    Default: '50'
    Description: The size of the Jellyfish database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.

  JellyfishDBMaxAllocatedStorage:
    Default: '1024'
    Description: The maximum storage auto-scale size of the Jellyfish database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '10240'
    ConstraintDescription: must be between 5 and 10240Gb.

  MultiAZ:
    Description: Enable MultiAZ database deployment
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t3.small
    AllowedValues:
    - db.t3.micro
    - db.t3.small
    - db.t3.medium
    - db.t3.large
    - db.t3.xlarge
    - db.t3.2xlarge
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge
    - db.r5.12xlarge
    - db.r5.24xlarge
    - db.r6g.large
    - db.r6g.xlarge
    - db.r6g.2xlarge
    - db.r6g.4xlarge
    - db.r6g.8xlarge
    - db.r6g.12xlarge
    - db.r6g.16xlarge
    - db.x1e.xlarge
    - db.x1e.2xlarge
    - db.x1e.4xlarge
    - db.x1e.8xlarge
    - db.x1e.16xlarge
    - db.x1e.32xlarge
    - db.m5.large
    - db.m5.xlarge
    - db.m5.2xlarge
    - db.m5.4xlarge
    - db.m5.12xlarge
    - db.m5.24xlarge
    - db.m6g.large
    - db.m6g.xlarge
    - db.m6g.2xlarge
    - db.m6g.4xlarge
    - db.m6g.8xlarge
    - db.m6g.12xlarge
    - db.m6g.16xlarge
    ConstraintDescription: must select a valid database instance type.

  JellyfishDBInstanceIdentifier:
    Description: RDS PostgreSQL database instance name
    Type: String
    Default: 'jellyfish'

  JellyfishDBParameterGroupFamily:
    Description: RDS PostgreSQL engine version
    Type: String
    Default: postgres13
    AllowedValues:
    - postgres12
    - postgres13
    ConstraintDescription: must select a valid database engine version

  JellyfishDBName:
    Default: jellyfish
    Description: The Jellyfish database name
    Type: String
    MinLength: '0'
    MaxLength: '64'

  JellyfishDBSnapshotIdentifier:
    Description: The Jellyfish database snapshot identifier
    Type: String
    MinLength: '0'
    MaxLength: '64'
    Default: ''

  JellyfishDBUsername:
    Default: jellyfish
    Description: The Jellyfish database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '64'

  JellyfishDBPassword:
    NoEcho: 'true'
    Description: The Jellyfish database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '64'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.

  KubernetesVPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID of the kubernetes cluster

  KubernetesSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of kubernetes node subnet IDs

  JellyfishDBStorageType:
    Description: Jellyfish Database instance class
    Default: gp2
    Type: String
    AllowedValues:
      - standard
      - gp2
      - io1
    ConstraintDescription: must select a valid database storage type.

  JellyfishDBStorageIops:
    Description: The number of reserved iops for 'io1' storage type
    Type: String
    Default: ''

  NetworkStack:
    Description: Stack containing network resources to import.
    Type: String
    Default: Resin-Deployment


Conditions:
  HasIdentifier: !Not [ !Equals [ '', !Ref JellyfishDBInstanceIdentifier ]]
  HasSnapshot: !Not [ !Equals [ '', !Ref JellyfishDBSnapshotIdentifier ]]
  HasIOPS: !Not [ !Equals [ '', !Ref JellyfishDBStorageIops ]]
  HasMultiAZEnabled: !Equals [ 'true', !Ref MultiAZ ]
  IsPostgres12: !Equals [ 'postgres12', !Ref JellyfishDBParameterGroupFamily ]
  IsPostgres13: !Equals [ 'postgres13', !Ref JellyfishDBParameterGroupFamily ]


Mappings:
  EngineMap:
    postgres12:
      EngineVersion: 12.7
    postgres13:
      EngineVersion: 13.6


Resources:
  JellyfishDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets available for the Jellyfish RDS DB Instance
      SubnetIds: !Ref KubernetesSubnetIDs

  JellyfishDBSecurityGroup:
    Type: 'AWS::RDS::DBSecurityGroup'
    Properties:
      GroupDescription: Allow PSQL access
      DBSecurityGroupIngress:
      - CIDRIP:
          Fn::ImportValue:
            !Sub "${NetworkStack}-PrimaryCidrBlock"
      - CIDRIP:
          Fn::ImportValue:
            !Sub "${NetworkStack}-SecondaryCidrBlock"
      EC2VpcId: !Ref KubernetesVPC

  EnhancedMonitoringRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  JellyfishDBParameterGroup12:
    Condition: IsPostgres12
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Jellyfish DB Parameter group
      Family: !Ref JellyfishDBParameterGroupFamily
      Parameters:
        autovacuum_analyze_scale_factor: '0.1'
        autovacuum_naptime: '60'
        autovacuum_vacuum_scale_factor: '0.2'
        log_autovacuum_min_duration: '100'
        log_min_duration_statement: '500'
        max_connections: '5000'
        pg_stat_statements.track: 'ALL'
        statement_timeout: '30000'
        work_mem: '64000'
        effective_io_concurrency: '200'
        random_page_cost: '1.1'
        # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.Replication.ReadReplicas.html#USER_PostgreSQL.Replication.ReadReplicas.Interruptions
        # https://aws.amazon.com/blogs/database/best-practices-for-amazon-rds-postgresql-replication/
        wal_keep_segments: '256'

  JellyfishDBParameterGroup13:
    Condition: IsPostgres13
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Jellyfish DB Parameter group
      Family: !Ref JellyfishDBParameterGroupFamily
      Parameters:
        autovacuum_analyze_scale_factor: '0.1'
        autovacuum_naptime: '60'
        autovacuum_vacuum_scale_factor: '0.2'
        autovacuum_vacuum_insert_scale_factor: '0.2'
        autovacuum_vacuum_insert_threshold: '1000'
        effective_io_concurrency: '200'
        enable_incremental_sort: 'on'
        hash_mem_multiplier: '1'
        log_autovacuum_min_duration: '100'
        log_min_duration_statement: '500'
        log_min_duration_sample: '-1'
        log_parameter_max_length_on_error: '0'
        log_parameter_max_length: '-1'
        log_statement_sample_rate: '1'
        logical_decoding_work_mem: '65536'
        maintenance_io_concurrency: '10'
        max_connections: '5000'
        max_slot_wal_keep_size: '-1'
        pg_stat_statements.track: 'ALL'
        pg_stat_statements.track_planning: '1'
        random_page_cost: '1.1'
        rds.accepted_password_auth_method: 'md5+scram'
        statement_timeout: '30000'
        wal_keep_size: '8192'
        wal_skip_threshold: '2048'
        work_mem: '65536'

  JellyfishDB:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Retain
    Properties:
      DBInstanceIdentifier: !If
        - HasIdentifier
        - !Ref JellyfishDBInstanceIdentifier
        - !Ref AWS::NoValue
      DBName:
        Ref: JellyfishDBName
      DBSnapshotIdentifier: !If
        - HasSnapshot
        - !Ref JellyfishDBSnapshotIdentifier
        - !Ref AWS::NoValue
      AllocatedStorage:
        Ref: JellyfishDBAllocatedStorage
      MaxAllocatedStorage: !Ref JellyfishDBMaxAllocatedStorage
      DBInstanceClass:
        Ref: DBInstanceClass
      Engine: postgres
      EngineVersion: !FindInMap
        - EngineMap
        - !Ref JellyfishDBParameterGroupFamily
        - EngineVersion
      MasterUsername:
        Ref: JellyfishDBUsername
      MasterUserPassword:
        Ref: JellyfishDBPassword
      BackupRetentionPeriod: '7'
      DBSubnetGroupName:
        Ref: JellyfishDBSubnetGroup
      DBSecurityGroups:
        - Ref: JellyfishDBSecurityGroup
      MultiAZ: !If
        - HasMultiAZEnabled
        - true
        - false
      MonitoringInterval: 30
      MonitoringRoleArn:
        Fn::GetAtt:
        - EnhancedMonitoringRole
        - Arn
      PreferredBackupWindow: 03:00-03:30
      PreferredMaintenanceWindow: sun:03:30-sun:04:30
      PubliclyAccessible: false
      StorageType:
        Ref: JellyfishDBStorageType
      Iops: !If
        - HasIOPS
        - !Ref JellyfishDBStorageIops
        - !Ref AWS::NoValue
      DBParameterGroupName: !If
        - IsPostgres13
        - Ref: JellyfishDBParameterGroup13
        - Ref: JellyfishDBParameterGroup12
      Tags:
      - Key: Name
        Value: jellyfish


Outputs:
  dbEndpoint:
    Description: Connection string for the database
    Value:
      Fn::Join:
      - ''
      - - psql://
        - Fn::GetAtt:
          - JellyfishDB
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - JellyfishDB
          - Endpoint.Port
  JellyfishDB:
    Value:
      Ref: JellyfishDB
    Description: ID of JellyfishDB
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-JellyfishDB"
