AWSTemplateFormatVersion: 2010-09-09

Parameters:
  KubernetesVPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID of the kubernetes cluster

  KubernetesSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of kubernetes node subnet IDs

  CacheNodeType:
    Description: The instance type the nodes will launch under.
    Type: String
    Default: cache.m6g.large
    # https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html
    # https://aws.amazon.com/elasticache/pricing/
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.m6g.large
      - cache.m6g.xlarge
      - cache.m6g.2xlarge
      - cache.m6g.4xlarge
      - cache.m6g.8xlarge
      - cache.m6g.12xlarge
      - cache.m6g.16xlarge
      - cache.r6g.large
      - cache.r6g.xlarge
      - cache.r6g.2xlarge
      - cache.r6g.4xlarge
      - cache.r6g.8xlarge
      - cache.r6g.12xlarge
      - cache.r6g.16xlarge

  NetworkStack:
    Description: Stack containing network resources to import.
    Type: String
    Default: Resin-Deployment


Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Jellyfish Redis cluster
      SecurityGroupIngress:
        - CidrIp:
            Fn::ImportValue:
              !Sub "${NetworkStack}-PrimaryCidrBlock"
          FromPort: 6379
          ToPort: 6379
          IpProtocol: tcp
        - CidrIp:
            Fn::ImportValue:
              !Sub "${NetworkStack}-SecondaryCidrBlock"
          FromPort: 6379
          ToPort: 6379
          IpProtocol: tcp
      VpcId: !Ref KubernetesVPC

  SubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: Subnet Group for Jellyfish Redis cluster
      SubnetIds: !Ref KubernetesSubnetIDs

  ReplicationGroup:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      ReplicationGroupDescription: Jellyfish Redis Cluster
      CacheNodeType: !Ref CacheNodeType
      Engine: redis
      NumCacheClusters: 2
      MultiAZEnabled: true
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      AtRestEncryptionEnabled: true
      CacheSubnetGroupName: !Ref SubnetGroup
      SecurityGroupIds:
        - !Ref SecurityGroup


Outputs:
  PrimaryEndPointAddress:
    Description: The DNS address of the primary read-write cache node.
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-PrimaryEndPointAddress'

  PrimaryEndPointPort:
    Description: The number of the port that the primary read-write cache engine is listening on.
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-PrimaryEndPointPort'

  ReadEndPointAddresses:
    Description: A string with a list of endpoints for the primary and read-only replicas. The order of the addresses maps to the order of the ports from the ReadEndPoint.Ports attribute.
    Value: !GetAtt ReplicationGroup.ReadEndPoint.Addresses
    Export:
      Name: !Sub '${AWS::StackName}-ReadEndPointAddresses'

  ReadEndPointPorts:
    Description: A string with a list of ports for the read-only replicas. The order of the ports maps to the order of the addresses from the ReadEndPoint.Addresses attribute.
    Value: !GetAtt ReplicationGroup.ReadEndPoint.Ports
    Export:
      Name: !Sub '${AWS::StackName}-ReadEndPointPorts'
