name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets:
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      # --- custom workflow secrets
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY_PUSH }}
      CUSTOM_JOB_SECRET_1: ${{ secrets.AWS_ACCESS_KEY_ID }}
      CUSTOM_JOB_SECRET_2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    with:
      # disable default balena action and handle in custom action(s) instead
      balena_slugs: ""
      # https://github.com/actions/runner/issues/1979
      jobs_timeout_minutes: 60
