name: Flowzone
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@87344fc86113238a25472a27d86403026802c5de
    secrets: inherit
    with:
      # disable default balena action and handle in custom action(s) instead
      balena_slugs: ""
      # https://github.com/actions/runner/issues/1979
      jobs_timeout_minutes: 60
      protect_branch: false
